FROM gradle:8-jdk21 AS build
WORKDIR /app
COPY . .
RUN gradle :document-service:bootJar -x test --no-daemon

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/document-service/build/libs/document-service.jar app.jar
ENTRYPOINT ["java", "-XX:+UseContainerSupport", "-jar", "app.jar"]
